'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import { usePathname } from 'next/navigation'
import Footer from '~/components/layouts/Footer'
import NavBar from '~/components/layouts/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname()
  return (
    <html lang='en'>
      <body className={inter.className}>
        {pathname !== '/auth' ? (
          <>
            <NavBar />
            {children}
            <Footer />
          </>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  )
}
